const beard = {
  event_type: {
    id: 1003864,
    title: 'Beard',
    slug: 'beard',
    length: 45,
    hidden: false,
    position: 0,
    userId: null,
    teamId: 17483,
    scheduleId: null,
    eventName: null,
    timeZone: null,
    periodType: 'UNLIMITED',
    periodStartDate: null,
    periodEndDate: null,
    periodDays: null,
    periodCountCalendarDays: null,
    requiresConfirmation: false,
    recurringEvent: null,
    disableGuests: true,
    hideCalendarNotes: false,
    minimumBookingNotice: 120,
    beforeEventBuffer: 0,
    afterEventBuffer: 0,
    schedulingType: 'MANAGED',
    price: 0,
    currency: 'usd',
    slotInterval: null,
    parentId: null,
    successRedirectUrl: null,
    description: 'Best haircut ever',
    locations: null,
    metadata: {},
    seatsPerTimeSlot: null,
    seatsShowAttendees: false,
    seatsShowAvailabilityCount: true,
    bookingFields: null,
    bookingLimits: null,
    onlyShowFirstAvailableSlot: false,
    durationLimits: null,
    children: [],
    hosts: [],
    customInputs: [],
    link: 'https://cal.com/team/studio-h/beard'
  }
}
